from enum import StrEnum


class AuditAction(StrEnum):
    # ===== User =====
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    USER_ACTIVATE = "USER_ACTIVATE"
    USER_DEACTIVATE = "USER_DEACTIVATE"

    # ===== Auth =====
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_REFRESH_FAILED = "AUTH_REFRESH_FAILED"
    AUTH_REVOKE_ALL_SESSIONS = "AUTH_REVOKE_ALL_SESSIONS"
    AUTH_ROTATE_REFRESH = "AUTH_ROTATE_REFRESH"

    # ===== Role / Permission =====
    ROLE_ASSIGN = "ROLE_ASSIGN"
    ROLE_REVOKE = "ROLE_REVOKE"
    PERMISSION_GRANT = "PERMISSION_GRANT"
    PERMISSION_REVOKE = "PERMISSION_REVOKE"

    # ===== System =====
    SYSTEM_JOB = "SYSTEM_JOB"
